name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: team_4S46tTsSRuLglk95ISdWDxlE
  VERCEL_PROJECT_ID: prj_Ep4jeqGu1d3aAUOSuG3Yrk9qjsv9
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=VXf6FXkrAmPO1BMAt8vdbiuV
      - name: Build Project Artifacts
        run: vercel build --token=VXf6FXkrAmPO1BMAt8vdbiuV
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=VXf6FXkrAmPO1BMAt8vdbiuV
