name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: team_4S46tTsSRuLglk95ISdWDxlE
  VERCEL_PROJECT_ID: prj_Ep4jeqGu1d3aAUOSuG3Yrk9qjsv9
on:
  push:
    branches:
      - master
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=VXf6FXkrAmPO1BMAt8vdbiuV
      - name: Build Project Artifacts
        run: vercel build --prod --token=VXf6FXkrAmPO1BMAt8vdbiuV
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=VXf6FXkrAmPO1BMAt8vdbiuV
